<div class="container mt-3">
    <h3 class="text-center"><a href="/cadastros" class="text-dark">Cadastros</a>/Funcionário</h3>
    <hr>
    <form method="post" class=" mx-auto border p-3">  
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Nome:</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Endereço:</label>
                    <input type="text" class="form-control">
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Telefone:</label>
                    <input type="text" class="form-control">
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Salário:</label>
                    <input type="text" class="form-control">
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Departamento:</label>
                    <select class="form-control">
                        <option value="1">Contrução</option>
                    </select>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Departamento que gerencia:</label>
                    <select class="form-control">
                        <option value="1">Nenhum</option>
                    </select>
                </div>
            </div>
            <div class="text-center col-sm-12">
                <button class="btn btn-success w-50 mt-3 ">Cadastrar</button>
            </div>
        </div>                                                
    </form>

</div>    
