<div class="container mt-3">
    <h3 class="text-center"><a href="/cadastros" class="text-dark">Cadastros</a>/Departamento</h3>
    <hr>
    <form method="post" class=" mx-auto border p-3">  
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Nome:</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Localização:</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="text-center col-sm-12">
                <button class="btn btn-success w-50 mt-3 ">Cadastrar</button>
            </div>
        </div>                                       

        
    </form>

</div>    
