<div class="container mt-3">
    <h3 class="text-center">Cadastros</h3>
    <hr>
    <div class="row">        
        <div class="col-sm-4 mb-2">
            <a href="cadastros/funcionario" >
                <div class="card text-center p-2">
                    <i class="fas fa-user icon"></i>
                    <div class="card-body">
                        <h5 class="card-title">Funcionários</h5>                    
                    </div>
                </div>
            </a>            
        </div>               
        <div class="col-sm-4 mb-2">
            <a href="cadastros/departamento">
                <div class="card text-center p-2">
                    <i class="fas fa-building icon"></i>
                    <div class="card-body">
                        <h5 class="card-title">Departamentos</h5>                    
                    </div>
                </div>
            </a>
        </div>               
        <div class="col-sm-4 mb-2">
            <a href="cadastros/projeto">
                <div class="card text-center p-2">
                    <i class="fas fa-archive icon"></i>
                    <div class="card-body">
                        <h5 class="card-title">Projetos</h5>                    
                    </div>
                </div>
            </a>
        </div>               
    </div>
</div>

<style>    
    .icon {
        font-size: 100pt;
    }
</style>